# Generated by Django 5.1.4 on 2025-01-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_messages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterField(
            model_name='products',
            name='striked_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
