# Generated by Django 5.1.4 on 2025-01-14 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_cartitem_order_cartitem_date_added_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='date_added',
        ),
    ]
