# Generated by Django 5.1.4 on 2025-01-14 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_cartitem_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='notes',
        ),
    ]
