# Generated by Django 5.1.4 on 2025-01-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_cartitem_date_added_remove_cartitem_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
