# Generated by Django 5.1.4 on 2025-01-14 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_cartitem_note_cartitem_terms_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='note',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='terms_accepted',
        ),
    ]
