# Generated by Django 5.1.4 on 2025-01-14 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='terms_accepted',
        ),
    ]
