# Generated by Django 5.1.4 on 2025-01-14 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_checkout_terms_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='item',
        ),
    ]
