# Generated by Django 5.1.4 on 2025-01-14 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_checkout_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('bank_transfer', 'Direct Bank Transfer'), ('cheque', 'Cheque Payment'), ('paypal', 'PayPal'), ('card', 'Credit Card')], default='bank_transfer', max_length=50)),
                ('card_name', models.CharField(blank=True, max_length=100, null=True)),
                ('card_type', models.CharField(blank=True, max_length=50, null=True)),
                ('card_number', models.CharField(blank=True, max_length=20, null=True)),
                ('card_cvv', models.CharField(blank=True, max_length=4, null=True)),
                ('card_expiry', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.order')),
            ],
        ),
    ]
