# Generated by Django 5.1.4 on 2025-01-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_deals_products_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='deals',
            field=models.ManyToManyField(max_length=20, to='app.deals'),
        ),
    ]
