# Generated by Django 5.1.4 on 2025-01-16 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_products_deals'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Deals',
            new_name='Labels',
        ),
    ]
