# Generated by Django 5.1.4 on 2025-01-16 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_rename_deals_labels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='deals',
            new_name='labels',
        ),
    ]
